[package]
name = "ckb-ez"
version = "0.1.1"
edition = "2021"
description = "CKB Easy is an experimental project that aims to provide human-friendly interfaces for common CKB operations."
license = "MIT"

[dependencies]
ckb-types = "0.116.1"
